apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodes-app-deployment
  labels:
    app: notes-app
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: yrueshgrg/notes-k8s
          ports:
            - containerPort: 8000
